services:
    tg528.bitsMailLogin.listener:
        class: tg528\bitsMailLogin\event\listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
